version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - api

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "password123*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"